language: python

python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"

jdk: oraclejdk7

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  matrix:
    - TOX_ENV=pep8
    - TOX_ENV=cdh
    - TOX_ENV=hdp
    - TOX_ENV=nonhdfs
    - TOX_ENV=docs

matrix:
  allow_failures:
    - python: "3.4"
    - python: "3.3"
sudo: false

cache:
  - $HOME/.pip-cache

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_failure:
  - cat /home/travis/build/spotify/luigi/.tox/cdh/log/cdh-1.log
