language: python

python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"

jdk: oraclejdk7

services:
  - elasticsearch

env:
  global:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - POSTGRES_USER=postgres
  matrix:
    - TOX_ENV=pep8
    - TOX_ENV=cdh
    - TOX_ENV=nonhdfs
    - TOX_ENV=docs

sudo: false

cache:
  - $HOME/.pip-cache

install:
  - pip install tox

before_script:
  - psql -c 'create database spotify;' -U postgres

  # allow ssh loopback
  - ssh-keygen -t rsa -N '' -C '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh -o StrictHostKeyChecking=no localhost true

script:
  - tox -e $TOX_ENV

after_failure:
  - cat /home/travis/build/spotify/luigi/.tox/cdh/log/cdh-1.log

branches:
  only:
    - master
